### ISSUE TITLE
questions about meshblu.json

### ISSUE THREAD

**Issue by eternaltao** [octoblu/meshblu-email-password-authenticator#1]
there not exists a file named meshblu.json should I create one ?

When I   sudo npm start  the   "email-password-site"  and sign up a email,  the "meshblu-authenticator-email-password" 

 reports:

I am b0fc0631-f42e-401d-9fd9-e0b97b8d02f9
listening at localhost:3003
OPTIONS /devices 204 5.067 ms - -
/home/dev/workspace/meshblu-authenticator-email-password/node_modules/meshblu-db/node_modules/meshblu-http/node_modules/node-rsa/src/NodeRSA.js:309
            throw Error("It is not private key");
                  ^
...
...
...

How can I fix the problem or how can I get the right  private key in meshblu.json? 

I need some help~  thanks very much.

**Comment by kmariano** [comment]
The problem is that your meshblu-authenticator-email-password does not have a public/private key pair generated on the device.  Do the following: 
1. Install meshblu-util (npm install -g meshblu-util)
2. generate a public private key for the meshblu-authenticator-email-password using the following command:

```
meshblu-util keygen -s [meshblu-server:meshblu-port]  [path/to/meshblu-authenticator-email-password/meshblu.json]
```

This will generate a public/private keypair for the device and store the private key in the meshblu.json file. This should fix the error.

**Comment by redaphid** [comment]
You probably also need to make a meshblu.json file, if you haven't already :).

This is a file that you use to identify which "device" the service is running as in Meshblu. It contains the uuid & token that represents your id & password into the system.

You can specify this in a variety of ways, including environment variables, but the meshblu.json file is the easiest.

You can use the command-line tool Koshin mentioned above to accomplish this, via:

`meshblu-util register > meshblu.json`

You'll want to run the command Koshin mentioned after this command is complete.

**Comment by eternaltao** [comment]
Thanks a lot. I got the meshblu.json file with privateKey sucessed. 

But the problem  ------------ "throw Error("It is not private key");"  still exists.



code in server.coffee:      
=======================================================
 32 meshbludb = new MeshbluDB meshbluJSON
 33 
 34 meshbludb.findOne uuid: meshbluJSON.uuid, (error, device) ->
 35   if error?
 36     console.error error.message, error.stack
 37     process.exit 1
 38 
 39   console.log "I am #{device.uuid}"
 40   console.log device
 41   meshbludb.setPrivateKey(device.privateKey) unless meshbludb.privateKey
 42 
 43   routes = new Routes app, meshbluJSON, meshbludb
 44   routes.register()
 45 
 46   app.listen port, =>
 47     console.log "listening at localhost:#{port}"
========================================================


There neither exists meshbludb.privateKey nor exists device.privateKey,  

I changed 
meshbludb.setPrivateKey(device.privateKey) unless meshbludb.privateKey
to
meshbludb.setPrivateKey(meshbluJSON.privateKey) unless meshbludb.privateKey

It's OK

Should I do like this  or there's something wrong what I did?

**Comment by eternaltao** [comment]
Thanks a lot. I got the meshblu.json file with privateKey sucessed.

But the problem ------------ "throw Error("It is not private key");" still exists.

code in server.coffee:

```
32 meshbludb = new MeshbluDB meshbluJSON
33 
34 meshbludb.findOne uuid: meshbluJSON.uuid, (error, device) ->
35 if error?
36 console.error error.message, error.stack
37 process.exit 1
38 
39 console.log "I am #{device.uuid}"
40 console.log device
41 meshbludb.setPrivateKey(device.privateKey) unless meshbludb.privateKey
42 
43 routes = new Routes app, meshbluJSON, meshbludb
44 routes.register()
45 
46 app.listen port, =>
47 console.log "listening at localhost:#{port}"
```

There neither exists meshbludb.privateKey nor exists device.privateKey,

I changed 
meshbludb.setPrivateKey(device.privateKey) unless meshbludb.privateKey
to
meshbludb.setPrivateKey(meshbluJSON.privateKey) unless meshbludb.privateKey

It's OK

Should I do like this or there's something wrong what I did?
